//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzariaJulubom
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery
    {
        public int id { get; set; }
        public int id_pedido { get; set; }
        public int id_cliente { get; set; }
        public Nullable<int> id_entregador { get; set; }
        public bool processado { get; set; }
        public int quantidade { get; set; }
        public string categoria { get; set; }
        public Nullable<int> id_produto { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual pedido pedido { get; set; }
        public virtual produto produto { get; set; }
    }
}
