//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzariaJulubom
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pro_chefeEntities : DbContext
    {
        public pro_chefeEntities()
            : base("name=pro_chefeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<delivery> delivery { get; set; }
        public virtual DbSet<ingrediente> ingrediente { get; set; }
        public virtual DbSet<itens_pedido> itens_pedido { get; set; }
        public virtual DbSet<mesa> mesa { get; set; }
        public virtual DbSet<pedido> pedido { get; set; }
        public virtual DbSet<produto> produto { get; set; }
        public virtual DbSet<tipo_usuario> tipo_usuario { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<valor_mesa> valor_mesa { get; set; }
    }
}
