//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzariaJulubom
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pedido()
        {
            this.delivery = new HashSet<delivery>();
            this.itens_pedido = new HashSet<itens_pedido>();
        }
    
        public int id { get; set; }
        public System.DateTime data { get; set; }
        public Nullable<int> id_mesa { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public Nullable<bool> delivery2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<delivery> delivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<itens_pedido> itens_pedido { get; set; }
        public virtual mesa mesa { get; set; }
    }
}
